[profile.default]

solc_version = '0.8.18'

src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 1_000

remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "erc721a/=lib/erc721a/contracts/",
  "operator-filter-registry/=lib/operator-filter-registry/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
